# -*- coding: utf-8 -*-
"""exercícios

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dT0XtchHx3wMmYWwewl3LcMcIq4_jgc5

# Python

# Olá mundo
"""

mensagem="Olá mundo"
print(mensagem)

"""# Entrada de valores"""

num = 3
num = input('Informe um número:')
print(f'O número informado foi {num}')

"""# Boletim Simples"""

soma_notas = 0
aluno = str(input('por favor, informe o nome do aluno:'))
for i in range(4):
    nota = int(input(f'Informe a {i+1}ª nota:'))
    soma_notas += nota
media = soma_notas/4
print(f'A média do aluno {aluno} é {media}')

"""# Soma"""

num = num1 = 0
q = int(input('Quantos números você deseja somar:'))
for i in range(q):
  num = int(input(f'Informe o {i+1}º número:'))
  num1 += num
print(f'A soma dos {q} números é {num1}')

"""#                                             basico de variaveis"""

var = 90
var

var = 10
VAR = 100
print(var)
print(VAR)

# Int = numeros inteiros
Var = 10
print(Var)
# Float = numero com vírgula
VAR = 10.9
print(VAR)
#str = palavras
var = "arroz"
print(var)
# todas as palavras tem que estar em ""

var = 12
Var = 12.5
VAR = "B"
print(var)
print(type(var))
print(Var)
print(type(Var))
print(VAR)
print(type(VAR))
# TYPE e ultizado para classificar o tipo de variavel
# type e print é usado para imprimir a variavel

var = 2
Var = 3.5
x1 = 2
print(var+Var)                            # Soma do int e do float
print(var*x1)                             # divisão do int  com int
print(Var/x1)                             # multiplicação

# Para imprimir texto e valores com o comando print é necessário converter os números em texto através do comando str(nome_da_variável).
x1 = 4
x2 = 'texto aleatorio'
print("conteudo de x1="+ str(x1) +", conteudo de4 x2="+ x2)

x1 = 4
x2 = 5                                            # não funciona se nn estiver str
x3 = 6
x4 = 7
x5 = 8
x6 =(2*5)/10+9
print("x6 = "+str(x6))

x1 = 'a'
x2 = 'bra'
x3 = 'ca'
x4 = 'dra'
X1 = x1 + x2 + x3 + x4 + x2
print(X1)

"""        Saída e entrada de dados"""

input('Digite seu nome: ')                            # Entrada e saída de texto

a = input('Digite um numero: ')
a = float(a)
b = input('Digite outro numero: ')
b = float(b)
resultado = a + b
print(resultado)

"""                                                  Coleção de dados"""

# Lista
# Lista são coleção de dados
X =[ 1, 2,3,4,5] # Valores int
Y =[1.2,3.4,5.6] # valores float
Z =['a','b','c','d','e','f'] # valores str
print(X)
print(X[0])
print(Y[1])
print(X[2])
print(X[3])
print(Z[4])

X = [1,2,3,45,6,]
len(X)                          # fornece o quantidade de numeros na lista

"""#Exercícios sobre a lista

É uma coleção ordenada e mutável de valores que permite valores duplicados

Listas: criação e acesso aos elementos
"""

x=[1,2,3,4,5,6]                             #Lista de valores tipo Int
y=['a,b,c,d,e,f']                            #Lista de valores tipo str
z=[1.2,1.31,1.4]                            #Lista de valores tipo float
print(x)
print(y)
print(z)

"""                                          Listas: acesso, manipulação e alteração"""

x=[3,4,5,6,67]
print('x[0]='+ str(x[0]))                     # O que estas nas aspas copia
print('x[1]='+ str(x[2]))                     # É (o + str) puxa a respota do X
print(x[-2])                                  # Se o numero for negativo a incógnita da lista será decrescente
print(x[3])                                   # Len = fornece o número da lista
print(x[-4])                                  # -3 significa a posição
print("len(x)=" + str(len(x)) )               # para colocar mais de um numero tem que colocar ":"
print(x[len(x)-3])
print('x[:4]=' + str(x[:4]))

"""Comandos uteis:

range serve para especificar uma faixa de valores;

list transforma uma faixa de valores em uma lista;

len fornece o total de elementos da lista;

count conta o número de ocorrência de um determinado valor;

max retorna o elemento de maior valor;

min retorna o elemento de menor valor;

index retorna o índice na lista do valor especificado;

sort ordenação de valores em ordem crescente (reverse = False) ou decrescente (reverse = True).

exercícios
"""

+A = [3,4,5,10]
soma1 = list() #soma1 = []
for i in A:
  soma1.append(i+1)
print (soma1)
   #soma1

A = [0,0,5,3,2,7,4,10,4,7]
N = list()
for i in A:
  if i% 2==0:
    N += [i*i] # N = N + [i*i]
print ("valor da lista N:", N)

"""#                                                        Jogo da forca"""

print('*********************************')
print('***Bem vindo ao jogo da Forca!***')
print('*********************************')
palavra_secreta = 'banana'
letras_acertadas = ['_', '_', '_', '_', '_', '_']
print(letras_acertadas)
acertou = False
enforcou = False
erros = 0
while (not acertou and not enforcou):
    chute = input("Qual letra?")
    if(chute in palavra_secreta):
        posicao = 0
        for letra in palavra_secreta:
            if (chute.upper() == letra.upper()):
              letras_acertadas[posicao] = letra
            posicao += 1
    else:
        erros += 1
    acertou = '_' not in letras_acertadas
    enforcou = erros == 6
    print(letras_acertadas)
if(acertou):
    print('\nVocê ganhou!!\n')
else:
    print('\nVocê perdeu!!\n')
print('Fim do jogo')

"""# gerador de senha"""

import random

senha=""
caracteres="zaq12xvfr4bgr5nhts!@#$%&*"
for digito in range (8):
    aleatorio=random.choice(caracteres)
    senha+= aleatorio
print("_"*20)
print(senha)
print("_"*20)

"""# Juros"""

depósito = float(input("Digite o valor do depósito: "))
taxa = float(input("digite uma taxa de juros:"))
mês = 1
saldo = depósito
while mês<=24:                                    # while significa "enquanto".
    saldo  =saldo + (saldo * (taxa / 100))
    print(f"saldo do mês {mês} é de R$ {saldo:10.2f}")
    mês += 1
print(f"O ganho obtido com os juros foi de R${saldo-depósito:8.2f}.")
#Esse tipo de string permite inserir expressões ou variáveis diretamente dentro de chaves {}, tornando a formatação de strings mais simples e legível.

"""# comando in

é um operador que verifica se um valor está presente dentro de uma sequência ou iterável
"""

def main():
  texto = input("Digite um texto:")
  n = len(texto)
  vogais = ['a','e','i','o','u','A','E','I','O','U']
  nv = 0
  for letra in texto:
    for vogal in vogais:
      if letra == vogal:
        nv+=1
  print("%f" %(nv/n))
main()

"""#                                                                   strings imutáveis"""

nome= "programação"
print(nome[4])      # Acessa a letra na posição 4
nome_alterado = "b" + nome[1:]            # B + rogramção
print(nome_alterado)
nome=nome_alterado
print(nome)

"""# expressão logica

A= 150, B=20, C=10, D=Falso, E=verdadeiro

Gearenciador do processador que resolve  conta matematica
"""

A= 150; B=20; C=10; D=False; E=True
(E and not D) and (A>(B*C)) or (B<C)

"""Validação de CPF"""

NOVO_CPF=list(input('Digite um cpf para ser validado>>>'))
NOVO_CPF_STRING=" ".join(NOVO_CPF)                             # O join significa que ele esta juntando todos os elementos da lista NOVO_CPF em uma única string, sem espaço entre eles(por isso usou as aspas)
def validacao_cpf():
  if len(NOVO_CPF)==11:
    primeiro1=int(NOVO_CPF[0])*10
    primeiro2=int(NOVO_CPF[1])*9
    primeiro3=int(NOVO_CPF[2])*8
    primeiro4=int(NOVO_CPF[3])*7
    primeiro5=int(NOVO_CPF[4])*6
    primeiro6=int(NOVO_CPF[5])*5
    primeiro7=int(NOVO_CPF[6])*4
    primeiro8=int(NOVO_CPF[7])*3
    primeiro9=int(NOVO_CPF[8])*2

    seg_primeiro1=int(NOVO_CPF[0])*11
    seg_primeiro2=int(NOVO_CPF[1])*10
    seg_primeiro3=int(NOVO_CPF[2])*9
    seg_primeiro4=int(NOVO_CPF[3])*8
    seg_primeiro5=int(NOVO_CPF[4])*7
    seg_primeiro6=int(NOVO_CPF[5])*6
    seg_primeiro7=int(NOVO_CPF[6])*5
    seg_primeiro8=int(NOVO_CPF[7])*4
    seg_primeiro9=int(NOVO_CPF[8])*3
    seg_primeiro10=int(NOVO_CPF[9])*2

    soma_validacao=(primeiro1+primeiro2+primeiro3+primeiro4+primeiro5+primeiro6+primeiro7+primeiro8+primeiro9)
    divisao_validacao=(soma_validacao // 11)
    resto=(soma_validacao - (11 * divisao_validacao))

    soma_validacao2=(seg_primeiro1+seg_primeiro2+seg_primeiro3+seg_primeiro4+seg_primeiro5+seg_primeiro6+seg_primeiro7+seg_primeiro8+seg_primeiro9)
    divisao_validacao2=(soma_validacao2 // 11)
    resto2=(soma_validacao2 - (11 * divisao_validacao2))

    antepenultimo_digito_cpf=(int(NOVO_CPF[8]))
    penultimo_digito_cpf=(int(NOVO_CPF[9]))
    ultimo_digito_cpf=(int(NOVO_CPF[10]))

    val_1 = False
    val_2= False
    val_3 = False
    val_4 = False

"""# Área de um circulo

# Área de um quadrado
"""

# vai caculas a área de um trabalho e depois vai mosta o dobro
somma = quadrado = 0
quadrado = float(input(f'informe a medida de um lado de um quadrado:'))
área = quadrado * 4
dobro = área * 2
print(f'O dobrp da área {área} do quadrado {dobro}')

"""# Conversão de medida"""

# Programa para coonverter metros por centimetros
medidas=0
metros= float(input('Informe as medidas em metros'))                          # pega o valor digitado pelo usuario e converte pra numero com virgula
centimentros= metros*100
print(f'{metros:2f} metros informados equivalem a {centimentros:.1f} centimentros.')

raio = float(input("Qual a medida do raio? R:"))
área = 3.14 *(raio**2)
print( f' A área  do cirsulo corresponde a {área:.2f} cm de área.')                                 # .2f Formata com duas casas decimais



"""# Hora trabalhada"""

# Faça um programa que exige quanto você ganha por horas e quanto vc trabalha no mês
print('-=' *30)
# Faça um programa que exige quanto você ganha por horas e quanto vc trabalha no mês
print('-=' *30)
print('Cáculos de horas trabalhadas')
print('-=' *30)
valor_hora =  float(input(' Informe o valor das horas trabaladas R$:'))
horas_trabalhadas = float(input('Informe, quantas horas foram trabalhadas'))
sálario =  valor_hora*horas_trabalhadas
if __name__ == '__main__':
if __name__ == '__main__'                                                                    #Esta condição verifica se a variável __name__
  print(f'O sálario, conforme as informações informadas, é de R${sálario:.2f}')              #tem o valor __main__. Se sim, o código dentro
                                                                                             #do bloco if é executado. Se não (por exemplo,
                                                                                             #se o script for importado como um módulo), o código
                                                                                             #dentro do bloco if não é executado

def dois(a, b):
    print(a * b)

resultado = dois(2, 5)
print(resultado)

lista = []
for i in range(3):
    lista.append(i * 2)
print(lista)

num = [3, 6, 9, 12, 15]
soma = 0
for i in range(1, len(num), 2):
    soma += num[i]
print(soma)

def aprovado(n1, n2, n3):
    media = (n1 + n2 + n3) / 3
    if media >= 6:
        return "Aprovado"
    else:
        return "Reprovado"

print(aprovado(3, 10, 5))

a=int(input(" Digite um núemro:"))
print(a)

